elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: elastic

keycloak:
  realm: test
  host: http://test:8443

logging:
  level:
    ROOT: info

rest-client:
  base-url: "http://localhost:${wiremock.server.port:8001}"
  categories:
    readTimeout: 300

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 1

resilience4j.retry:
  configs:
    default:
      maxAttempts: 2
      waitDuration: 100