elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: elastic

keycloak:
  realm: test
  host: http://test:8443

logging:
  level:
    ROOT: WARN
    br.com.jkavdev.fullcycle.admin.catalogo: WARN